//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string Numero { get; set; }
        public string Modulo { get; set; }
        public string IDCliente { get; set; }
        public string Estado { get; set; }
    }
}
